---
title: "depletion-observation-example"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{depletion-observation-example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(isw)
```


```{r}
library(patchwork)
library(units)
library(png)
library(dplyr)
library(ggplot2)
library(tidyr)

well_config_img <- readPNG("../inst/figs/pumping_observation_wells.png")

# example from Glover
# x1 <- set_units(c(1, 5, 10, 25, 50) * 1e3, 'ft')
D <- set_units(200, 'ft')
K <- set_units(0.001, 'ft/sec')
# t_sec <- set_units(1, "year") # sec in a year
V <- 0.2
# 
# r <- x1 # ft
# x1
# df1 <- tibble(r = r, K = K, D = D, V = V, t = t_sec)
# get_aquifer_drawdown_ratio(df1)
# get_aquifer_drawdown_ratio(r = r, K = K, D = D, V = V, t = t_sec*2)
```


```{r}
txt_size <- 12
theme_basic <- ggplot2::theme(
  line = ggplot2::element_line(size = 1, color = "black"), 
  panel.background = ggplot2::element_rect(fill = "white"), 
  legend.text = element_text(size = txt_size*0.9, color = "black"), 
  axis.title.x = ggplot2::element_text(size = txt_size, colour = "black"), 
  axis.title.y = ggplot2::element_text(size = txt_size, angle = 90, colour = "black"), 
  legend.title = element_text(size = txt_size, color = "black"))


theme_std <- theme_basic %+replace% theme(
  panel.border = ggplot2::element_rect(fill = NA, colour = "black", size = 1), 
  panel.grid.major = ggplot2::element_blank(), 
  panel.grid.minor = ggplot2::element_blank(), axis.line = ggplot2::element_blank(), 
  axis.ticks.x = ggplot2::element_line(colour = "black", size = 0.5), 
  axis.ticks.y = ggplot2::element_line(colour = "black", size = 0.5), 
  axis.ticks.length = ggplot2::unit(1, "mm"), 
  axis.text.x = ggplot2::element_text(size = txt_size*0.9, colour = "black"), 
  axis.text.y = ggplot2::element_text(size = txt_size*0.9,  colour = "black", hjust = 1))

theme_diagram <- theme_basic %+replace% 
  theme(
  panel.border = ggplot2::element_rect(fill = NA, colour = NA, size = 1), 
  panel.grid.major = ggplot2::element_blank(), 
  panel.grid.minor = ggplot2::element_blank(), 
  axis.line = ggplot2::element_blank(), 
  axis.ticks.x = ggplot2::element_blank() , 
  axis.ticks.y = ggplot2::element_blank(), 
  axis.ticks.length = ggplot2::unit(1, "mm"), 
  axis.text.x = ggplot2::element_blank(), 
  axis.text.y = element_blank(), 
  axis.title.x = ggplot2::element_blank(), 
  axis.title.y = ggplot2::element_blank()) %+replace%
  theme(legend.position = c(0.8, 0.75), legend.box = 'vertical', legend.title = element_blank())
```


```{r}

# x2 <- set_units(1e3, 'ft')
# y <- set_units(1e3, 'ft')
# get_depletion_from_pumping(x1 = x1, x2 = x2, y = y, K = K, D = D, V = V, t = t_sec)

locations <- tribble(~x1, ~y, ~`Obs. well`, ~`Pumping well`,
                     0.2, 1.5, "a", "c",
                     0.8, 1.5, "a", "d",
                     0.2, 0, "b", "c",
                     0.8, 0, "b", "d") %>%
  mutate(across(all_of(c("x1","y")), function(x) set_units(x,"mi")), id = row_number())
df <- locations %>%
  crossing(t = set_units(c(0.05, seq(0.1,5, by = 0.1)),'year')) %>%
  mutate(x2 = set_units(5280/2,"ft"), K = K, D = D, V = V)


df_calcs <- df %>%
  bind_cols(as_tibble(get_depletion_from_pumping(.)))

df_calcs
```


```{r, fig.height=5}
p_depletion_fraction <- ggplot(df_calcs,aes(as.numeric(t), as.numeric(stream_depletion_fraction), color = `Pumping well`)) + 
  geom_line(aes(group = id)) +
  labs(x = "Time since pumping onset, years",
       y = "Fraction of well abstraction\nfrom stream depletion") +
  expand_limits(y= c(0,1)) +
  theme_std %+replace% 
  theme(legend.position = "none")
p_drawdown_ratio <- ggplot(df_calcs,aes(as.numeric(t), as.numeric(-aquifer_drawdown_ratio), color = `Pumping well`)) + 
  geom_line(aes(group = id)) +
  geom_point(data = df_calcs %>% dplyr::filter(abs(as.numeric(t)) %% 0.5 < 0.01),aes(shape = `Obs. well`), size = 3, stroke = 1) +
  scale_shape_manual(values = c(0, 5)) +
  expand_limits(y= c(0)) +
  labs(x = "Time since pumping onset, years",
       y = "Drawdown (ft) per\ncusec pumping") +
  theme_std %+replace% theme(legend.position = "none")

p_depletion_fraction / p_drawdown_ratio
```


```{r}
p_drawdown_depletion <- ggplot(df_calcs, aes(as.numeric(-aquifer_drawdown_ratio), as.numeric(stream_depletion_fraction), color = `Pumping well`)) + 
  geom_point(data = df_calcs %>% dplyr::filter(abs(as.numeric(t)) %% 0.5 < 0.15),aes(shape = `Obs. well`), size = 3, stroke = 1) +
  scale_shape_manual(values = c(0, 5)) +
  # expand_limits(y= c(0)) +
  labs(x = "Drawdown (ft) per\ncusec pumping",
       y = "Fraction of well abstraction\nfrom stream depletion") +
  theme_std %+replace% theme(legend.position = "none")
p_drawdown_depletion
```



```{r}
ggplot(locations) + 
  geom_point(aes(x1, y, color = `Pumping well`, shape = `Obs. well`)) + theme_std
```




```{r fig.width = 5.5, fig.height = 4}
# x2 <- set_units(1e3, 'ft')
# y <- set_units(1e3, 'ft')
# get_depletion_from_pumping(x1 = x1, x2 = x2, y = y, K = K, D = D, V = V, t = t_sec)

elapsed_time_years <- c(0, 1, 4, 5)
df <- tibble(t = set_units(elapsed_time_years, "year"),
             period = factor(elapsed_time_years > 1.1, levels = c(F, T), labels = c("0-1 year","4-5 years")),
             x1 = set_units(2, "mi"),
             y = set_units(0.01, "mi"),
             K = K, D = D, V = V) %>%
  mutate(`Elapsed time` = factor(as.character(t), as.character(elapsed_time_years), labels = paste(elapsed_time_years, "years"))) %>%
  crossing(x2 = set_units(seq(0.02, 8, by = 0.1),"mi")) %>%
  group_by(period, x2) %>%
  mutate(first_or_second = factor(row_number(), levels = c(1,2), labels = c("Initial water table", "One year later"))) %>%
  group_by() %>%
  bind_cols(as_tibble(get_depletion_from_pumping(.)))


df_ribbon <- df %>%
  mutate(aquifer_drawdown_ratio = as.numeric(aquifer_drawdown_ratio)) %>%
  dplyr::select(period, first_or_second, t, aquifer_drawdown_ratio, x2, `Elapsed time`) %>%
  pivot_wider(id_cols = c("period", "x2"), names_from = "first_or_second", values_from = "aquifer_drawdown_ratio")


# ggplot(df) + 
#   geom_line(aes(as.numeric(x2), as.numeric(aquifer_drawdown_ratio), color = `Elapsed time`)) + 
#   scale_color_discrete() +
#   labs(y = "Groundwater levels (ft)", x = "Distance from river (mi)") +
#   theme_std %+replace% theme(legend.position = c(0.8, 0.3)) +
#   facet_wrap(~period, ncol = 1)



ggplot(df_ribbon) + 
  geom_ribbon(aes(as.numeric(x2), ymin = `Initial water table`, ymax = `One year later`, fill = 'Aquifer drawdown'), alpha = 0.7) + 
  geom_line(data = df, aes(as.numeric(x2), as.numeric(aquifer_drawdown_ratio), linetype = first_or_second)) + 
  scale_color_discrete() +
  scale_fill_manual("", values = "lightblue") +
  scale_linetype_manual("", values = c("dashed","solid")) +
  labs(y = "Groundwater levels (ft)", x = "Distance from river (mi)") +
  theme_diagram +
  facet_wrap(~period, ncol = 1)
```





