---
title: "Stream-depletion-and-aquifer-drawdown"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Stream-depletion-and-aquifer-drawdown}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(isw)
```


```{r}
library(patchwork)
library(units)
library(png)
library(tidyverse)

well_config_img <- readPNG("../inst/figs/pumping_observation_wells.png")

# example from Glover
x1 <- set_units(c(1, 5, 10, 25, 50) * 1e3, 'ft')
D <- set_units(200, 'ft')
K <- set_units(0.001, 'ft/sec')
t_sec <- set_units(1, "year") # sec in a year
V <- 0.2
# 
r <- x1 # ft
# x1
# df1 <- tibble(r = r, K = K, D = D, V = V, t = t_sec)
# get_aquifer_drawdown_ratio(df1)
get_aquifer_drawdown_ratio(r = r, K = K, D = D, V = V, t = t_sec*2)
```


```{r}
# 
# 
# 
# get stream depletion and effect on head at observation well
# x1 - distance of pumping well to stream
# x2 - distance of observation well to stream
# y - distance between pumping and observation well (parallel to stream)
# other variables from Glover (1954)
# get_depletion_of_well <- function(x1 = x1, x2 = x2, y = y, K = K, D = D, V = V, t = t) {

#   r_w <- sqrt(y^2 + (x2-x1)^2) # ft
#   r_wi <- sqrt(y^2 + (x2+x1)^2) # ft
# 
#   q_fraction <- get_q_fraction(x1 = x1, K = K, D = D, V = V, t = t) # %
#   ds_w <- get_s_ratio(r = r_w, K = K, D = D, V = V, t = t) # ft / flowrate
#   dw_wi <- -get_s_ratio(r = r_wi, K = K, D = D, V = V, t = t) # ft / flowrate
#   return(list(q_fraction = q_fraction, s_ratio = ds_w + dw_wi))
# }
```


```{r}
x2 <- set_units(1e3,'ft')
y <- set_units(1e3,'ft')
get_depletion_from_pumping(x1 = x1, x2 = x2, y = y, K = K, D = D, V = V, t = t_sec)

df <- crossing(x1 = set_units(seq(0, 4, by = 0.02) * 5280,'ft'),
               y = set_units(seq(0, 3, by = 0.02) * 5280,'ft'),
               nesting(t = c(t_sec*2, t_sec*5, t_sec * 10), years = c(2, 5, 10))) %>%
  mutate(x2 = set_units(5280/2,"ft"), K = K, D = D, V = V,
         years = factor(years, levels = c(2, 5, 10), labels = paste(c(2, 5, 10), "years")))

# df <- df %>%
#   dplyr::filter(t == t_sec/2 | ((x1 %in% (seq(0, 4, by = 0.1) * 5280)) & y %in% (seq(0, 3, by = 0.1) * 5280)))

# df %>% dplyr::filter(t == t_sec) #%>% pull(x1) %>% unique()
```


```{r}
df_calcs <- df %>%
  mutate(x1 = x1 + set_units(10,'ft'),
         y = y + set_units(10,'ft')) %>%
  bind_cols(as_tibble(get_depletion_from_pumping(.))) %>%
  mutate(x1 = replace(x1, x1 <= set_units(10,'ft'), set_units(0,'ft')),
         y = replace(y, y <= set_units(10,'ft'), set_units(0,'ft')))


df2 <- df %>%
  bind_cols(df_calcs %>% dplyr::select(stream_depletion_fraction, aquifer_drawdown_ratio))
```

```{r}
theme_std <- ggplot2::theme(line = ggplot2::element_line(size = 1, 
        color = "black"), panel.background = ggplot2::element_rect(fill = "white"), 
        panel.border = ggplot2::element_rect(fill = NA, colour = "black", 
            size = 1), panel.grid.major = ggplot2::element_blank(), 
        panel.grid.minor = ggplot2::element_blank(), axis.line = ggplot2::element_blank(), 
        axis.ticks.x = ggplot2::element_line(colour = "black", 
            size = 0.5), axis.ticks.y = ggplot2::element_line(colour = "black", 
            size = 0.5), axis.ticks.length = ggplot2::unit(1, 
            "mm"), axis.text.x = ggplot2::element_text(size = 9, 
            colour = "black"), axis.text.y = ggplot2::element_text(size = 9, 
            colour = "black", hjust = 1), legend.text = element_text(size = 9, 
            color = "black"), axis.title.x = ggplot2::element_text(size = 10, 
            colour = "black"), axis.title.y = ggplot2::element_text(size = 10, 
            angle = 90, colour = "black"), legend.title = element_text(size = 10, 
            color = "black"))
```



```{r}
# df2 %>% dplyr::select(x1, y, t, s_ratio) %>% pivot_wider(names_from = "t", values_from = "s_ratio")

p_q_fraction <- ggplot(df2) +
  geom_line(aes(as.numeric(x1/5280), stream_depletion_fraction, color = years)) +
  labs(x = "East-West distance (x1, mi) from pumping well to river",
       y = "Fraction of well abstraction\nfrom stream depletion") +
  ylim(c(0, 1)) +
  scale_color_discrete("Years after\npumping initiates") +
  theme_std
p_q_fraction
```


```{r}
p_drawdown <- ggplot(df2 %>% dplyr::filter(aquifer_drawdown_ratio <= set_units(-1/100/12,'s/ft^2'))) +
  geom_raster(aes(as.numeric(x1/5280),as.numeric(y/5280), fill = -log(-as.numeric(aquifer_drawdown_ratio)))) +
  # geom_point(data = df2 %>% dplyr::filter(s_ratio <= -1/100/12, t == t_sec*10),
  #            aes(x1/5280,y/5280, color = -log(-s_ratio))) +
  scale_fill_viridis_c("Drawdown\n(ft) per cusec\npumping", limits = -log(c(16, 1/100/12)), breaks = -log(c(1/64/12, 1/16/12, 1/3/12, 1/12, 1/4, 1, 4, 16)), labels = c("1/64 in","1/16 in","1/4 in","1 in", "4 in", "1 ft", "4 ft", "16 ft")) +
  scale_color_viridis_c("Drawdown\n(ft) per cusec\npumping", breaks = -log(c(1/64/12, 1/16/12, 1/3/12, 1/12, 1/4, 1, 4, 16)), labels = c("1/64 in","1/16 in","1/4 in","1 in", "4 in", "1 ft", "4 ft", "16 ft")) +
  scale_size_continuous("Stream\ndepletion\nfraction") +
  # ggtitle() +
  labs(x = "East-West distance (x1, mi) from pumping well to river",
       y = "North-South distance (y, mi)\nfrom pumping well to observation well") +
  geom_vline(data = data.frame(x = c(0.25, 0.5, 1, 2, 3)), aes(xintercept = x, linetype = as.factor(x)), alpha = 0.4)+
  scale_linetype_manual(values = c("dotted", "dashed", "twodash", "longdash", "solid")) +
  guides(linetype = "none") +
  facet_wrap(~years, ncol = 1) + theme_std
p_drawdown
```


```{r}
# ggplot() +
#   geom_vline(data = NULL, aes(xintercept = c(0.25, 0.5, 1, 2, 3)* 5280))
# p_q_fraction /


transects_data <- df2 %>% dplyr::filter(x1 %in% (c(0.24, 0.5, 1, 2, 3)*5280))
p_drawdown_transects <- ggplot(transects_data) + #, t %in% (c(2, 5) * t_sec))) +
  geom_line(data = transects_data %>% dplyr::filter(years == "5 years") %>% dplyr::select(-years),
            aes(as.numeric(-aquifer_drawdown_ratio), y/5280, linetype = as.factor(x1/5280)), alpha = 0.15) +
  geom_line(aes(as.numeric(-aquifer_drawdown_ratio), y/5280, color = years, linetype = as.factor(x1/5280))) +
  scale_color_discrete("Years after\npumping initiates") +
  scale_x_continuous("Drawdown (ft) per cusec pumping", limits = c(0, 2.5)) + facet_wrap(~years, ncol = 1) +
  scale_linetype_manual("Distance\nfrom well\nto river\n(x1, mi)",values = c("dotted", "dashed", "twodash", "longdash", "solid"), labels = c(0.25, 0.5, 1, 2, 3)) +
  guides(color = "none") +
  theme_std %+replace% theme(axis.title.y = element_blank())
p_drawdown_transects
```


```{r fig.width = 7, fig.height = 7}
p_well_config <- ggplot2::ggplot() + ggplot2::annotation_custom(grid::rasterGrob(well_config_img,
                                                                width=ggplot2::unit(1,"npc"),
                                                                height=ggplot2::unit(1,"npc")),
                                               -Inf, Inf, -Inf, Inf)

p_depletion_x <- p_q_fraction + p_well_config +
  p_drawdown + p_drawdown_transects +
  plot_layout(widths = c(3, 2), heights = c(1, 3)) +
  plot_annotation(title = paste0("Stream depletion and aquifer drawdown at observation well"),
                  subtitle = paste0(paste(rep("     ",10), collapse = ""),"x2 = 0.5 mile, ",D," ft aq. depth\n"))

p_depletion_x

# ggsave(paste0("stream_depletion_drawdown_aq",D,"ft.png"), p_depletion_x, path = out_path, width = 8, height = 8)
# set_units(set_units(1, "ft^3 / sec"), "acre * ft/year")
```

