#' Sixmile Creek example stream network
#'
#' Stream-flowline geometry for Sixmile Creek and its tributary Dorn Creek near
#' Waunakee, Wisconsin. The network surrounds the hypothetical pumping-well
#' location used in the `streamDepletr` introductory example.
#'
#' @format An `sf` object with one row per USGS 3D Hydrography Program
#'   flowline and the following fields:
#' \describe{
#'   \item{reach_id}{Character 3DHP flowline identifier.}
#'   \item{stream_name}{Character stream name: `"Sixmile Creek"` or
#'     `"Dorn Creek"`.}
#'   \item{geometry}{`MULTILINESTRING` geometry in NAD83 / UTM zone 16N
#'     (EPSG:26916).}
#' }
#'
#' @details
#' The data are generated by
#' `data-raw/sixmile-creek-stream-reaches.R` using
#' [get_usgs_stream_reaches()]. The script queries all 3DHP flowlines within
#' 10 kilometers of the example well at easting 295500 meters and northing
#' 4783200 meters, then retains flowlines named Sixmile Creek or Dorn Creek.
#' Because this object is a snapshot of the USGS service, rerunning the script
#' after a hydrography update may produce different geometry or identifiers.
#'
#' @source U.S. Geological Survey 3D Hydrography Program,
#'   \url{https://www.usgs.gov/3d-hydrography-program/access-3dhp-data-products}
#'
#' @usage data(sixmile_creek_stream_reaches)
#'
#' @keywords datasets
"sixmile_creek_stream_reaches"

#' Example pumping wells
#'
#' Two synthetic pumping wells used by the stream-depletion apportionment
#' examples and vignettes.
#'
#' @format An `sf` object with two point features and the following fields:
#' \describe{
#'   \item{pump_id}{Unique character pumping-well identifier.}
#'   \item{K}{Hydraulic conductivity with units of meters per second.}
#'   \item{D}{Aquifer thickness with units of meters.}
#'   \item{V}{Dimensionless drainable porosity.}
#'   \item{geometry}{Point geometry in WGS 84 / UTM zone 15N (EPSG:32615).}
#' }
#'
#' @details Generated by `data-raw/apportionment-example-data.R` together with
#'   [example_stream_reaches] and [example_observation_wells].
#'
#' @usage data(example_pumping_wells)
#'
#' @keywords datasets
"example_pumping_wells"

#' Example stream network
#'
#' A synthetic three-reach stream network used by the stream-depletion
#' apportionment examples and vignettes. Two upstream reaches meet at a
#' confluence and flow into one downstream reach.
#'
#' @format An `sf` object with one line feature per stream reach and the
#'   following fields:
#' \describe{
#'   \item{reach_id}{Unique character stream-reach identifier.}
#'   \item{geometry}{Line geometry in WGS 84 / UTM zone 15N (EPSG:32615).}
#' }
#'
#' @details Generated by `data-raw/apportionment-example-data.R` together with
#'   [example_pumping_wells] and [example_observation_wells].
#'
#' @usage data(example_stream_reaches)
#'
#' @keywords datasets
"example_stream_reaches"

#' Example observation wells
#'
#' Two synthetic observation wells used to demonstrate aquifer drawdown and
#' stream recovery in the stream-depletion apportionment examples and
#' vignettes.
#'
#' @format An `sf` object with two point features and the following fields:
#' \describe{
#'   \item{observation_id}{Unique character observation-well identifier.}
#'   \item{geometry}{Point geometry in WGS 84 / UTM zone 15N (EPSG:32615).}
#' }
#'
#' @details Generated by `data-raw/apportionment-example-data.R` together with
#'   [example_pumping_wells] and [example_stream_reaches].
#'
#' @usage data(example_observation_wells)
#'
#' @keywords datasets
"example_observation_wells"
