#' Example pumping wells
#'
#' Two synthetic pumping wells used by the stream-depletion apportionment
#' examples and vignettes.
#'
#' @format An `sf` object with two point features and the following fields:
#' \describe{
#'   \item{pump_id}{Unique character pumping-well identifier.}
#'   \item{K}{Hydraulic conductivity with units of meters per second.}
#'   \item{D}{Aquifer thickness with units of meters.}
#'   \item{V}{Dimensionless drainable porosity.}
#'   \item{well_diam}{Well diameter with units of meters.}
#'   \item{geometry}{Point geometry in WGS 84 / UTM zone 15N (EPSG:32615).}
#' }
#'
#' @details Generated by `data-raw/apportionment-example-data.R` together with
#'   [example_stream_reaches] and [example_observation_wells].
#'
#' @usage data(example_pumping_wells)
#'
#' @keywords datasets
"example_pumping_wells"

#' Example stream network
#'
#' A synthetic three-reach stream network used by the stream-depletion
#' apportionment examples and vignettes. Two upstream reaches meet at a
#' confluence and flow into one downstream reach.
#'
#' @format An `sf` object with one line feature per stream reach and the
#'   following fields:
#' \describe{
#'   \item{reach_id}{Unique character stream-reach identifier.}
#'   \item{geometry}{Line geometry in WGS 84 / UTM zone 15N (EPSG:32615).}
#' }
#'
#' @details Generated by `data-raw/apportionment-example-data.R` together with
#'   [example_pumping_wells] and [example_observation_wells].
#'
#' @usage data(example_stream_reaches)
#'
#' @keywords datasets
"example_stream_reaches"

#' Example observation wells
#'
#' Two synthetic observation wells used to demonstrate aquifer drawdown and
#' stream recovery in the stream-depletion apportionment examples and
#' vignettes.
#'
#' @format An `sf` object with two point features and the following fields:
#' \describe{
#'   \item{observation_id}{Unique character observation-well identifier.}
#'   \item{geometry}{Point geometry in WGS 84 / UTM zone 15N (EPSG:32615).}
#' }
#'
#' @details Generated by `data-raw/apportionment-example-data.R` together with
#'   [example_pumping_wells] and [example_stream_reaches].
#'
#' @usage data(example_observation_wells)
#'
#' @keywords datasets
"example_observation_wells"
